**Medidas del laboratorio**

$x_0$ = 0.5m  
$x_f$ = 1.3m  
$\Delta x$ = 0.4m  

Masa inicial con aleta: 0.197kg

Incertidumbre: 0.001kg

Deslizador solo: 0.187kg

Longitud aleta: 0.0116m

Bloque 1: 0.0213 m


Bloque 2: 0.03035 m

Bloque 3: 0.0425 m

Incertidumbre calibrador: 0.00005 m

Distancia entre fotosensores: 0.04m

***Experimento con bloque 1***

Serie 1: Masa regular

Serie 2: Masa 0.04Kg

Serie 3: Masa 0.1 kg

***Experimento con bloque 2***

Serie 4: Masa regular

Serie 5: Masa 0.04kg

Serie 6: Masa 0.1kg

***Experimento con bloque 3***

Serie 7: Masa regular 

Serie 8: Masa 0.04kg 

Serie 9: Masa 0.1kg

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

### Cálculo de Ángulos ###

In [8]:
b_1= 0.0213 
b_2= 0.03035
b_3= 0.0425

a_1=np.arcsin(b_1) #Ángulo del bloque 1 
a_1=np.degrees(a_1)

a_2=np.arcsin(b_2) #Ángulo del bloque 2
a_2=np.degrees(a_2)

a_3=np.arcsin(b_3) #Ángulo del bloque 3
a_3=np.degrees(a_3)

print(a_1, a_2, a_3)

1.2204924030276227 1.7391939797228742 2.4358042835065783

-----------------------------------------------------------------

### Importe de datos, calculo de promedios y desviaciónes ###

In [55]:
#Importamos los datos
names=[]
for i in range(1, 10):
    names.append("Set"+str(i)+".1")
    names.append("Set"+str(i)+".2")
data = pd.read_csv("../data/Dato exportado_090327.csv", skiprows=2,
                   usecols=[3, 5, 12, 14, 21, 23, 30, 32, 39, 41, 48, 50, 57, 59, 66, 68, 75, 77], names=names,
                   sep=";", decimal=",").dropna(how="all")
for i in range(1,10):
    data["Set" +str(i)+ ".2"] = data["Set" +str(i)+ ".2"].shift(periods=-1)
data = data.dropna().set_index(pd.Index(range(0,10)))
data_prom = pd.DataFrame(np.round(data.mean(), 4)).T
data_std = pd.DataFrame(np.round(data.std(ddof=1), 4)).T
data

,Set1.1,Set1.2,Set2.1,Set2.2,Set3.1,Set3.2,Set4.1,Set4.2,Set5.1,Set5.2,Set6.1,Set6.2,Set7.1,Set7.2,Set8.1,Set8.2,Set9.1,Set9.2
0,0.4101,0.5707,0.4076,0.5689,0.4077,0.5680,0.4863,0.6804,0.4866,0.6788,0.4858,0.6794,0.5719,0.7998,0.5742,0.8008,0.5733,0.7971
1,0.4097,0.5700,0.4078,0.5687,0.4085,0.5688,0.4865,0.6811,0.4879,0.6797,0.4861,0.6804,0.5730,0.8007,0.5735,0.8010,0.5769,0.7994
2,0.4109,0.5709,0.4079,0.5690,0.4068,0.5684,0.4874,0.6812,0.4869,0.6793,0.4857,0.6787,0.5751,0.8021,0.5738,0.8012,0.5762,0.7987
3,0.4103,0.5700,0.4085,0.5701,0.4062,0.5671,0.4858,0.6800,0.4872,0.6804,0.4860,0.6791,0.5732,0.8007,0.5744,0.8021,0.5756,0.7994
4,0.4103,0.5704,0.4093,0.5709,0.4079,0.5691,0.4859,0.6796,0.4864,0.6798,0.4856,0.6796,0.5726,0.7999,0.5726,0.7999,0.5759,0.7999
5,0.4100,0.5699,0.4101,0.5717,0.4067,0.5673,0.4849,0.6788,0.4859,0.6785,0.4855,0.6793,0.5717,0.8001,0.5736,0.8008,0.5757,0.7997
6,0.4088,0.5689,0.4091,0.5701,0.4064,0.5674,0.4856,0.6806,0.4867,0.6801,0.4861,0.6799,0.5727,0.8007,0.5730,0.7997,0.5761,0.8003
7,0.4087,0.5692,0.4096,0.5715,0.4090,0.5698,0.4875,0.6803,0.4871,0.6798,0.4850,0.6780,0.5742,0.8010,0.5736,0.7992,0.5754,0.7989
8,0.4104,0.5709,0.4093,0.5712,0.4072,0.5680,0.4876,0.6813,0.4861,0.6782,0.4857,0.6783,0.5737,0.8009,0.5739,0.8002,0.5756,0.7992
9,0.4096,0.5690,0.4092,0.5701,0.4071,0.5677,0.4873,0.6814,0.4863,0.6782,0.4844,0.6774,0.5738,0.8015,0.5750,0.7998,0.5758,0.7992

### Cálculo de alturas en el riel ###

In [19]:
#Bloque 1 altura 1
d_b1_h1 = d_f*np.sin(a_1)
b1_h1=b_1 - d_b1_h1 #Altura respecto a la superifcie

In [22]:
#Bloque 2 altura 2
d_b1_h2 = d_f*np.sin(a_1)
b1_h2=b_1 - d_b1_h2

In [23]:
#Bloque 2 altura 1 
d_b2_h1 = d_f*np.sin(a_2)
b2_h1=b_1 - d_b2_h1

In [24]:
#Bloque 2 altura 2
d_b2_h2 = d_f*np.sin(a_2)
b2_h2=b_2 - d_b2_h2

In [29]:
#Bloque 3 altura 1
d_b3_h1 = d_f*np.sin(a_3)
b3_h1=b_2 - d_b3_h1
b3_h3

0.02865

In [31]:
#Bloque 3 altura 2 
d_b3_h2 = 2*d_f*np.sin(a_3)
b3_h2=b_2 - d_b3_h2
b3_h2

0.026949999999999998